In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
print("Imported!")

Imported!

In [2]:
url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"
extracting_data = requests.get(url).text
wiki_data = BeautifulSoup(extracting_data, 'lxml')

In [3]:
column_names = ['Postalcode','Borough','Neighborhood']
toronto = pd.DataFrame(columns = column_names)

content = wiki_data.find('div', class_='mw-parser-output')
table = content.table.tbody
postcode = 0
borough = 0
neighborhood = 0

for tr in table.find_all('tr'):
    i = 0
    for td in tr.find_all('td'):
        if i == 0:
            postcode = td.text
            i = i + 1
        elif i == 1:
            borough = td.text
            i = i + 1
        elif i == 2: 
            neighborhood = td.text.strip('\n').replace(']','')
    toronto = toronto.append({'Postalcode': postcode,'Borough': borough,'Neighborhood': neighborhood},ignore_index=True)

In [4]:
lst=[]

for items in toronto['Postalcode']:
    lst.append(items)
lst

['\nM1ANot assigned\n\n',
 '\nM1BScarborough(Malvern / Rouge)\n\n',
 '\nM1CScarborough(Rouge Hill / Port Union / Highland Creek)\n\n',
 '\nM1EScarborough(Guildwood / Morningside / West Hill)\n\n',
 '\nM1GScarborough(Woburn)\n\n',
 '\nM1HScarborough(Cedarbrae)\n\n',
 '\nM1JScarborough(Scarborough Village)\n\n',
 '\nM1KScarborough(Kennedy Park / Ionview / East Birchmount Park)\n\n',
 '\nM1LScarborough(Golden Mile / Clairlea / Oakridge)\n\n',
 '\nM1MScarborough(Cliffside / Cliffcrest / Scarborough Village West)\n\n',
 '\nM1NScarborough(Birch Cliff / Cliffside West)\n\n',
 '\nM1PScarborough(Dorset Park / Wexford Heights / Scarborough Town Centre)\n\n',
 '\nM1RScarborough(Wexford / Maryvale)\n\n',
 '\nM1SScarborough(Agincourt) \n\n',
 "\nM1TScarborough(Clarks Corners / Tam O'Shanter / Sullivan)\n\n",
 "\nM1VScarborough(Milliken / Agincourt North / Steeles East / L'Amoreaux East)\n\n",
 "\nM1WScarborough(Steeles West / L'Amoreaux West)\n\n",
 '\nM1XScarborough(Upper Rouge)\n\n',
 '\nM1YNot assigned\n\n',
 '\nM1ZNot assigned\n\n']

In [5]:
for items in toronto['Borough']:
    lst.append(items)
for items in toronto['Neighborhood']:
    lst.append(items)
lst

['\nM1ANot assigned\n\n',
 '\nM1BScarborough(Malvern / Rouge)\n\n',
 '\nM1CScarborough(Rouge Hill / Port Union / Highland Creek)\n\n',
 '\nM1EScarborough(Guildwood / Morningside / West Hill)\n\n',
 '\nM1GScarborough(Woburn)\n\n',
 '\nM1HScarborough(Cedarbrae)\n\n',
 '\nM1JScarborough(Scarborough Village)\n\n',
 '\nM1KScarborough(Kennedy Park / Ionview / East Birchmount Park)\n\n',
 '\nM1LScarborough(Golden Mile / Clairlea / Oakridge)\n\n',
 '\nM1MScarborough(Cliffside / Cliffcrest / Scarborough Village West)\n\n',
 '\nM1NScarborough(Birch Cliff / Cliffside West)\n\n',
 '\nM1PScarborough(Dorset Park / Wexford Heights / Scarborough Town Centre)\n\n',
 '\nM1RScarborough(Wexford / Maryvale)\n\n',
 '\nM1SScarborough(Agincourt) \n\n',
 "\nM1TScarborough(Clarks Corners / Tam O'Shanter / Sullivan)\n\n",
 "\nM1VScarborough(Milliken / Agincourt North / Steeles East / L'Amoreaux East)\n\n",
 "\nM1WScarborough(Steeles West / L'Amoreaux West)\n\n",
 '\nM1XScarborough(Upper Rouge)\n\n',
 '\nM1YNot assigned\n\n',
 '\nM1ZNot assigned\n\n',
 '\nM2ANot assigned\n\n',
 '\nM2BNot assigned\n\n',
 '\nM2CNot assigned\n\n',
 '\nM2ENot assigned\n\n',
 '\nM2GNot assigned\n\n',
 '\nM2HNorth York(Hillcrest Village)\n\n',
 '\nM2JNorth York(Fairview / Henry Farm / Oriole)\n\n',
 '\nM2KNorth York(Bayview Village)\n\n',
 '\nM2LNorth York(York Mills / Silver Hills)\n\n',
 '\nM2MNorth York(Willowdale / Newtonbrook)\n\n',
 '\nM2NNorth York(Willowdale)South\n\n',
 '\nM2PNorth York(York Mills West)\n\n',
 '\nM2RNorth York(Willowdale)West\n\n',
 '\nM2SNot assigned\n\n',
 '\nM2TNot assigned\n\n',
 '\nM2VNot assigned\n\n',
 '\nM2WNot assigned\n\n',
 '\nM2XNot assigned\n\n',
 '\nM2YNot assigned\n\n',
 '\nM2ZNot assigned\n\n',
 'M9AEtobicoke(Islington Avenue)',
 'M9BEtobicoke(West Deane Park / Princess Gardens / Martin Grove / Islington / Cloverdale)',
 'M9CEtobicoke(Eringate / Bloordale Gardens / Old Burnhamthorpe / Markland Wood)',
 'M9ENot assigned',
 'M9GNot assigned',
 'M9HNot assigned',
 'M9JNot assigned',
 'M9KNot assigned',
 'M9LNorth York(Humber Summit)',
 'M9MNorth York(Humberlea / Emery)',
 'M9NYork(Weston)',
 'M9PEtobicoke(Westmount)',
 'M9REtobicoke(Kingsview Village / St. Phillips / Martin Grove Gardens / Richview Gardens)',
 'M9SNot assigned',
 'M9TNot assigned',
 'M9VEtobicoke(South Steeles / Silverstone / Humbergate / Jamestown / Mount Olive / Beaumond Heights / Thistletown / Albion Gardens)',
 'M9WEtobicokeNorthwest(Clairville / Humberwood / Woodbine Downs / West Humber / Kipling Heights / Rexdale / Elms / Tandridge / Old Rexdale)',
 'M9XNot assigned',
 'M9YNot assigned',
 'M9ZNot assigned']

In [6]:
new_list=[]
for value in lst:
    new_value=value.replace('\n', '')
    new_list.append(new_value)
new_list

['M1ANot assigned',
 'M1BScarborough(Malvern / Rouge)',
 'M1CScarborough(Rouge Hill / Port Union / Highland Creek)',
 'M1EScarborough(Guildwood / Morningside / West Hill)',
 'M1GScarborough(Woburn)',
 'M1HScarborough(Cedarbrae)',
 'M1JScarborough(Scarborough Village)',
 'M1KScarborough(Kennedy Park / Ionview / East Birchmount Park)',
 'M1LScarborough(Golden Mile / Clairlea / Oakridge)',
 'M1MScarborough(Cliffside / Cliffcrest / Scarborough Village West)',
 'M1NScarborough(Birch Cliff / Cliffside West)',
 'M1PScarborough(Dorset Park / Wexford Heights / Scarborough Town Centre)',
 'M1RScarborough(Wexford / Maryvale)',
 'M1SScarborough(Agincourt) ',
 "M1TScarborough(Clarks Corners / Tam O'Shanter / Sullivan)",
 "M1VScarborough(Milliken / Agincourt North / Steeles East / L'Amoreaux East)",
 "M1WScarborough(Steeles West / L'Amoreaux West)",
 'M1XScarborough(Upper Rouge)',
 'M1YNot assigned',
 'M1ZNot assigned',
 'M2ANot assigned',
 'M2BNot assigned',
 'M2CNot assigned',
 'M2ENot assigned',
 'M2GNot assigned',
 'M2HNorth York(Hillcrest Village)',
 'M2JNorth York(Fairview / Henry Farm / Oriole)',
 'M2KNorth York(Bayview Village)',
 'M2LNorth York(York Mills / Silver Hills)',
 'M2MNorth York(Willowdale / Newtonbrook)',
 'M2NNorth York(Willowdale)South',
 'M2PNorth York(York Mills West)',
 'M2RNorth York(Willowdale)West',
 'M2SNot assigned',
 'M2TNot assigned',
 'M2VNot assigned',
 'M2WNot assigned',
 'M2XNot assigned',
 'M2YNot assigned',
 'M2ZNot assigned',
 'M9AEtobicoke(Islington Avenue)',
 'M9BEtobicoke(West Deane Park / Princess Gardens / Martin Grove / Islington / Cloverdale)',
 'M9CEtobicoke(Eringate / Bloordale Gardens / Old Burnhamthorpe / Markland Wood)',
 'M9ENot assigned',
 'M9GNot assigned',
 'M9HNot assigned',
 'M9JNot assigned',
 'M9KNot assigned',
 'M9LNorth York(Humber Summit)',
 'M9MNorth York(Humberlea / Emery)',
 'M9NYork(Weston)',
 'M9PEtobicoke(Westmount)',
 'M9REtobicoke(Kingsview Village / St. Phillips / Martin Grove Gardens / Richview Gardens)',
 'M9SNot assigned',
 'M9TNot assigned',
 'M9VEtobicoke(South Steeles / Silverstone / Humbergate / Jamestown / Mount Olive / Beaumond Heights / Thistletown / Albion Gardens)',
 'M9WEtobicokeNorthwest(Clairville / Humberwood / Woodbine Downs / West Humber / Kipling Heights / Rexdale / Elms / Tandridge / Old Rexdale)',
 'M9XNot assigned',
 'M9YNot assigned',
 'M9ZNot assigned']

In [7]:
postal_list=[]
for value in new_list:
    postal_list.append(value[0:3])
postal_list

['M1A',
 'M1B',
 'M1C',
 'M1E',
 'M1G',
 'M1H',
 'M1J',
 'M1K',
 'M1L',
 'M1M',
 'M1N',
 'M1P',
 'M1R',
 'M1S',
 'M1T',
 'M1V',
 'M1W',
 'M1X',
 'M1Y',
 'M1Z',
 'M2A',
 'M2B',
 'M2C',
 'M2E',
 'M2G',
 'M2H',
 'M2J',
 'M2K',
 'M2L',
 'M2M',
 'M2N',
 'M2P',
 'M2R',
 'M2S',
 'M2T',
 'M2V',
 'M2W',
 'M2X',
 'M2Y',
 'M2Z',
 'M9A',
 'M9B',
 'M9C',
 'M9E',
 'M9G',
 'M9H',
 'M9J',
 'M9K',
 'M9L',
 'M9M',
 'M9N',
 'M9P',
 'M9R',
 'M9S',
 'M9T',
 'M9V',
 'M9W',
 'M9X',
 'M9Y',
 'M9Z']

In [8]:
borough_list=[]
for value in new_list:
    pos= value.find('(')
    new_value = value[3:pos]
    new_value = str(new_value)
    if new_value == 'Not assigne':
        new_value = new_value + 'd'
        borough_list.append(new_value)
    else:
        borough_list.append(new_value)
borough_list

['Not assigned',
 'Scarborough',
 'Scarborough',
 'Scarborough',
 'Scarborough',
 'Scarborough',
 'Scarborough',
 'Scarborough',
 'Scarborough',
 'Scarborough',
 'Scarborough',
 'Scarborough',
 'Scarborough',
 'Scarborough',
 'Scarborough',
 'Scarborough',
 'Scarborough',
 'Scarborough',
 'Not assigned',
 'Not assigned',
 'Not assigned',
 'Not assigned',
 'Not assigned',
 'Not assigned',
 'Not assigned',
 'North York',
 'North York',
 'North York',
 'North York',
 'North York',
 'North York',
 'North York',
 'North York',
 'Not assigned',
 'Not assigned',
 'Not assigned',
 'Not assigned',
 'Not assigned',
 'Not assigned',
 'Not assigned',
 'Etobicoke',
 'Etobicoke',
 'Etobicoke',
 'Not assigned',
 'Not assigned',
 'Not assigned',
 'Not assigned',
 'Not assigned',
 'North York',
 'North York',
 'York',
 'Etobicoke',
 'Etobicoke',
 'Not assigned',
 'Not assigned',
 'Etobicoke',
 'EtobicokeNorthwest',
 'Not assigned',
 'Not assigned',
 'Not assigned']

In [9]:
neighbourhood_list=[]
for value in new_list:
    pos1 = value.find('(')
    pos2 = value.find(')')
    neighbourhood_list.append(value[pos1+1:pos2])
neighbourhood_list

['M1ANot assigne',
 'Malvern / Rouge',
 'Rouge Hill / Port Union / Highland Creek',
 'Guildwood / Morningside / West Hill',
 'Woburn',
 'Cedarbrae',
 'Scarborough Village',
 'Kennedy Park / Ionview / East Birchmount Park',
 'Golden Mile / Clairlea / Oakridge',
 'Cliffside / Cliffcrest / Scarborough Village West',
 'Birch Cliff / Cliffside West',
 'Dorset Park / Wexford Heights / Scarborough Town Centre',
 'Wexford / Maryvale',
 'Agincourt',
 "Clarks Corners / Tam O'Shanter / Sullivan",
 "Milliken / Agincourt North / Steeles East / L'Amoreaux East",
 "Steeles West / L'Amoreaux West",
 'Upper Rouge',
 'M1YNot assigne',
 'M1ZNot assigne',
 'M2ANot assigne',
 'M2BNot assigne',
 'M2CNot assigne',
 'M2ENot assigne',
 'M2GNot assigne',
 'Hillcrest Village',
 'Fairview / Henry Farm / Oriole',
 'Bayview Village',
 'York Mills / Silver Hills',
 'Willowdale / Newtonbrook',
 'Willowdale',
 'York Mills West',
 'Willowdale',
 'M2SNot assigne',
 'M2TNot assigne',
 'M2VNot assigne',
 'M2WNot assigne',
 'M2XNot assigne',
 'M2YNot assigne',
 'M2ZNot assigne',
 'Islington Avenue',
 'West Deane Park / Princess Gardens / Martin Grove / Islington / Cloverdale',
 'Eringate / Bloordale Gardens / Old Burnhamthorpe / Markland Wood',
 'M9ENot assigne',
 'M9GNot assigne',
 'M9HNot assigne',
 'M9JNot assigne',
 'M9KNot assigne',
 'Humber Summit',
 'Humberlea / Emery',
 'Weston',
 'Westmount',
 'Kingsview Village / St. Phillips / Martin Grove Gardens / Richview Gardens',
 'M9SNot assigne',
 'M9TNot assigne',
 'South Steeles / Silverstone / Humbergate / Jamestown / Mount Olive / Beaumond Heights / Thistletown / Albion Gardens',
 'Clairville / Humberwood / Woodbine Downs / West Humber / Kipling Heights / Rexdale / Elms / Tandridge / Old Rexdale',
 'M9XNot assigne',
 'M9YNot assigne',
 'M9ZNot assigne']

In [10]:
new_neighbourhood_list= []
for value in neighbourhood_list:
    new_value=value.replace('/', ',')
    new_neighbourhood_list.append(new_value)
new_neighbourhood_list

['M1ANot assigne',
 'Malvern , Rouge',
 'Rouge Hill , Port Union , Highland Creek',
 'Guildwood , Morningside , West Hill',
 'Woburn',
 'Cedarbrae',
 'Scarborough Village',
 'Kennedy Park , Ionview , East Birchmount Park',
 'Golden Mile , Clairlea , Oakridge',
 'Cliffside , Cliffcrest , Scarborough Village West',
 'Birch Cliff , Cliffside West',
 'Dorset Park , Wexford Heights , Scarborough Town Centre',
 'Wexford , Maryvale',
 'Agincourt',
 "Clarks Corners , Tam O'Shanter , Sullivan",
 "Milliken , Agincourt North , Steeles East , L'Amoreaux East",
 "Steeles West , L'Amoreaux West",
 'Upper Rouge',
 'M1YNot assigne',
 'M1ZNot assigne',
 'M2ANot assigne',
 'M2BNot assigne',
 'M2CNot assigne',
 'M2ENot assigne',
 'M2GNot assigne',
 'Hillcrest Village',
 'Fairview , Henry Farm , Oriole',
 'Bayview Village',
 'York Mills , Silver Hills',
 'Willowdale , Newtonbrook',
 'Willowdale',
 'York Mills West',
 'Willowdale',
 'M2SNot assigne',
 'M2TNot assigne',
 'M2VNot assigne',
 'M2WNot assigne',
 'M2XNot assigne',
 'M2YNot assigne',
 'M2ZNot assigne',
 'Islington Avenue',
 'West Deane Park , Princess Gardens , Martin Grove , Islington , Cloverdale',
 'Eringate , Bloordale Gardens , Old Burnhamthorpe , Markland Wood',
 'M9ENot assigne',
 'M9GNot assigne',
 'M9HNot assigne',
 'M9JNot assigne',
 'M9KNot assigne',
 'Humber Summit',
 'Humberlea , Emery',
 'Weston',
 'Westmount',
 'Kingsview Village , St. Phillips , Martin Grove Gardens , Richview Gardens',
 'M9SNot assigne',
 'M9TNot assigne',
 'South Steeles , Silverstone , Humbergate , Jamestown , Mount Olive , Beaumond Heights , Thistletown , Albion Gardens',
 'Clairville , Humberwood , Woodbine Downs , West Humber , Kipling Heights , Rexdale , Elms , Tandridge , Old Rexdale',
 'M9XNot assigne',
 'M9YNot assigne',
 'M9ZNot assigne']

In [11]:
new_neighbourhood_list1= []
for value in new_neighbourhood_list:
    value = str(value)
    #print(value[3:])
    if value[3:] == 'Not assigne':
        #print(value)
        new_value= value.replace(value, 'NA')
        new_neighbourhood_list1.append(new_value)
    else:
        new_neighbourhood_list1.append(value)
new_neighbourhood_list1

['NA',
 'Malvern , Rouge',
 'Rouge Hill , Port Union , Highland Creek',
 'Guildwood , Morningside , West Hill',
 'Woburn',
 'Cedarbrae',
 'Scarborough Village',
 'Kennedy Park , Ionview , East Birchmount Park',
 'Golden Mile , Clairlea , Oakridge',
 'Cliffside , Cliffcrest , Scarborough Village West',
 'Birch Cliff , Cliffside West',
 'Dorset Park , Wexford Heights , Scarborough Town Centre',
 'Wexford , Maryvale',
 'Agincourt',
 "Clarks Corners , Tam O'Shanter , Sullivan",
 "Milliken , Agincourt North , Steeles East , L'Amoreaux East",
 "Steeles West , L'Amoreaux West",
 'Upper Rouge',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Hillcrest Village',
 'Fairview , Henry Farm , Oriole',
 'Bayview Village',
 'York Mills , Silver Hills',
 'Willowdale , Newtonbrook',
 'Willowdale',
 'York Mills West',
 'Willowdale',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Islington Avenue',
 'West Deane Park , Princess Gardens , Martin Grove , Islington , Cloverdale',
 'Eringate , Bloordale Gardens , Old Burnhamthorpe , Markland Wood',
 'NA',
 'NA',
 'NA',
 'NA',
 'NA',
 'Humber Summit',
 'Humberlea , Emery',
 'Weston',
 'Westmount',
 'Kingsview Village , St. Phillips , Martin Grove Gardens , Richview Gardens',
 'NA',
 'NA',
 'South Steeles , Silverstone , Humbergate , Jamestown , Mount Olive , Beaumond Heights , Thistletown , Albion Gardens',
 'Clairville , Humberwood , Woodbine Downs , West Humber , Kipling Heights , Rexdale , Elms , Tandridge , Old Rexdale',
 'NA',
 'NA',
 'NA']

In [12]:
del toronto

In [13]:
column_names = ['Postalcode','Borough','Neighborhood']
toronto = pd.DataFrame(columns = column_names)
toronto

Empty DataFrame
Columns: [Postalcode, Borough, Neighborhood]
Index: []

In [14]:
for x in range(0,60):
    post = postal_list[x]
    boro = borough_list[x]
    neighbour = new_neighbourhood_list1[x]
    toronto = toronto.append({'Postalcode': post,'Borough': boro,'Neighborhood': neighbour},ignore_index=True)

In [15]:
toronto

,Postalcode,Borough,Neighborhood
0,M1A,Not assigned,NA
1,M1B,Scarborough,"Malvern , Rouge"
2,M1C,Scarborough,"Rouge Hill , Port Union , Highland Creek"
3,M1E,Scarborough,"Guildwood , Morningside , West Hill"
4,M1G,Scarborough,Woburn
5,M1H,Scarborough,Cedarbrae
6,M1J,Scarborough,Scarborough Village
7,M1K,Scarborough,"Kennedy Park , Ionview , East Birchmount Park"
8,M1L,Scarborough,"Golden Mile , Clairlea , Oakridge"
9,M1M,Scarborough,"Cliffside , Cliffcrest , Scarborough Village West"
10,M1N,Scarborough,"Birch Cliff , Cliffside West"
11,M1P,Scarborough,"Dorset Park , Wexford Heights , Scarborough To..."
12,M1R,Scarborough,"Wexford , Maryvale"
13,M1S,Scarborough,Agincourt
14,M1T,Scarborough,"Clarks Corners , Tam O'Shanter , Sullivan"
15,M1V,Scarborough,"Milliken , Agincourt North , Steeles East , L'..."
16,M1W,Scarborough,"Steeles West , L'Amoreaux West"
17,M1X,Scarborough,Upper Rouge
18,M1Y,Not assigned,NA
19,M1Z,Not assigned,NA
20,M2A,Not assigned,NA
21,M2B,Not assigned,NA
22,M2C,Not assigned,NA
23,M2E,Not assigned,NA
24,M2G,Not assigned,NA
25,M2H,North York,Hillcrest Village
26,M2J,North York,"Fairview , Henry Farm , Oriole"
27,M2K,North York,Bayview Village
28,M2L,North York,"York Mills , Silver Hills"
29,M2M,North York,"Willowdale , Newtonbrook"
30,M2N,North York,Willowdale
31,M2P,North York,York Mills West
32,M2R,North York,Willowdale
33,M2S,Not assigned,NA
34,M2T,Not assigned,NA
35,M2V,Not assigned,NA
36,M2W,Not assigned,NA
37,M2X,Not assigned,NA
38,M2Y,Not assigned,NA
39,M2Z,Not assigned,NA
40,M9A,Etobicoke,Islington Avenue
41,M9B,Etobicoke,"West Deane Park , Princess Gardens , Martin Gr..."
42,M9C,Etobicoke,"Eringate , Bloordale Gardens , Old Burnhamthor..."
43,M9E,Not assigned,NA
44,M9G,Not assigned,NA
45,M9H,Not assigned,NA
46,M9J,Not assigned,NA
47,M9K,Not assigned,NA
48,M9L,North York,Humber Summit
49,M9M,North York,"Humberlea , Emery"
50,M9N,York,Weston
51,M9P,Etobicoke,Westmount
52,M9R,Etobicoke,"Kingsview Village , St. Phillips , Martin Grov..."
53,M9S,Not assigned,NA
54,M9T,Not assigned,NA
55,M9V,Etobicoke,"South Steeles , Silverstone , Humbergate , Jam..."
56,M9W,EtobicokeNorthwest,"Clairville , Humberwood , Woodbine Downs , Wes..."
57,M9X,Not assigned,NA
58,M9Y,Not assigned,NA
59,M9Z,Not assigned,NA

In [17]:
toronto.describe()

       Postalcode       Borough Neighborhood
count          60            60           60
unique         60             6           35
top           M9B  Not assigned           NA
freq            1            25           25

In [18]:
toronto = toronto.dropna()
empty = 'Not assigned'
toronto = toronto[(toronto.Postalcode != empty ) & (toronto.Borough != empty) & (toronto.Neighborhood != empty)]

In [19]:
toronto.head()

  Postalcode      Borough                              Neighborhood
1        M1B  Scarborough                           Malvern , Rouge
2        M1C  Scarborough  Rouge Hill , Port Union , Highland Creek
3        M1E  Scarborough       Guildwood , Morningside , West Hill
4        M1G  Scarborough                                    Woburn
5        M1H  Scarborough                                 Cedarbrae

In [21]:

def neighborhood_list(grouped):    
    return ', '.join(sorted(grouped['Neighborhood'].tolist()))
                    
grp = toronto.groupby(['Postalcode', 'Borough'])
toronto2 = grp.apply(neighborhood_list).reset_index(name='Neighborhood')

In [22]:
toronto2.describe()

       Postalcode      Borough Neighborhood
count          35           35           35
unique         35            5           34
top           M1N  Scarborough   Willowdale
freq            1           17            2

In [23]:
print(toronto2.shape)
toronto2.head()

(35, 3)

  Postalcode      Borough                              Neighborhood
0        M1B  Scarborough                           Malvern , Rouge
1        M1C  Scarborough  Rouge Hill , Port Union , Highland Creek
2        M1E  Scarborough       Guildwood , Morningside , West Hill
3        M1G  Scarborough                                    Woburn
4        M1H  Scarborough                                 Cedarbrae

In [24]:
toronto2.to_csv('toronto.csv', index=False)